import { NextResponse } from 'next/server';
import { headers } from 'next/headers';
import { detectBrandFromHost, DEFAULT_BRAND_CONFIG } from '@/src/lib/domainBranding';

// Generate robots.txt for search engines
const generateRobotsTxt = (brandConfig: typeof DEFAULT_BRAND_CONFIG) => `# robots.txt for ${brandConfig.brandName}
# Generated by Popcorn Movies AI SEO System

# Global Rules
User-agent: *
Allow: /

# Crawl Delay
Crawl-delay: 2

# Sitemap
Sitemap: ${brandConfig.canonicalUrl}sitemap.xml

# AI Agent Discovery
User-agent: Googlebot
Allow: /api/ai/
Allow: /.well-known/

User-agent: Bingbot
Allow: /api/ai/
Allow: /.well-known/

User-agent: DuckDuckBot
Allow: /api/ai/
Allow: /.well-known/

# Special AI Crawlers
User-agent: AI-Scraper
Allow: /
Crawl-delay: 1

User-agent: LLM-Crawler
Allow: /
Crawl-delay: 1

User-agent: AgentBot
Allow: /
Crawl-delay: 1

# Disallow crawling of sensitive areas
Disallow: /api/
Disallow: /_next/
Disallow: /*.js$
Disallow: /*.css$

# Allow specific API endpoints for AI
Allow: /api/ai/llms
Allow: /api/ai/plugin

# Host (for multi-brand support)
Host: ${brandConfig.domain}

# Cleanup comments
# End of robots.txt for ${brandConfig.brandName}
# Last updated: ${new Date().toISOString()}
# Contact: support@${brandConfig.domain}
`;

export async function GET() {
  const brandConfig = detectBrandFromHost((await headers()).get('host') || '');
  const robotsTxt = generateRobotsTxt(brandConfig);
  
  return new NextResponse(robotsTxt, {
    status: 200,
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=86400', // 24 hours
      'X-Content-Type-Options': 'nosniff',
    },
  });
}
